### ISSUE TITLE
BOL Changes to satisfy Crude/Gas Requirements

### ISSUE THREAD

**Issue by mkhraisha** [w3c-ccg/traceability-vocab#115]
The following are a list of items that we need to have tracked on the BOL credential:

* ArrivalDate (not just expected arrival as outlined by ParcelDelivery)
* ShippingDate ( date the item was shipped)

* ValuePerItem
* TotalOrderValue

* freightChargeTerms -- https://www.thebalancesmb.com/types-of-freight-charges-1361580
* Batch Number -- Number that identifies products as received in a batch by the carrier.

This is specific to Crude oil, as the volume at injection may change from volume at delivery.
* OpeningVolume
* ClosingVolume
* Observations -- Crude oil is measured while it flows during the pipeline and this is included in the delivery ticket (BOL)

**Comment by mkhraisha** [comment]
@OR13 I think the cleanest way to tackle this is to open a PR with the requested changes and then we argue over it there.
alternatively i can show these changes as a concrete proposal on the issue and we take it from there.

**Comment by mprorock** [comment]
@mkhraisha we are very similar and have a lot of overlap.  one approach is to identify what is common, and then subclass for commodity specific - only note is that in ag we refer to lot rather than batch number on your top list of items

e.g. a common BOL - then BOLCrude which has all the fields from BOL, and then adds the crude specific - then code can be written to handle the superclass, and still behave ok if it knows what to do with subclass additional parameters - key thing there, is that additional properties should be then set to true on the superclass

**Comment by OR13** [comment]
yes, I expect we will need to add fields / refactor into smaller more reusable components, ideally, our use of generators, would make it possible to upgrade by simply making the change in 1 or 2 places.

**Comment by OR13** [comment]
Discussed on call, proposal to raise a PR.

**Comment by mkhraisha** [comment]
Apologies for delay on this, will tackle this for next week's meeting.

**Comment by OR13** [comment]
@mkhraisha pending PR

**Comment by mprorock** [comment]
@mkhraisha any updates, or can this be closed

**Comment by nissimsan** [comment]
@mkhraisha, this seems completely stale. We're closing the issue, please re-open if needed.
