### ISSUE TITLE
Example Generation Adding @Context

### ISSUE THREAD

**Issue by adam-lerner** [w3c-ccg/traceability-vocab#150]
In several spots in the Traceability Vocab, I've noticed that examples are being generated with contexts embedded into the credential subject and other properties. These additional contexts are not needed and we should fix the example generator to not display them. See example below for `credentialSubject `and `relatedDocuments`:

``` "credentialSubject": {
    "@context": [
      "https://w3id.org/traceability/v1"
    ],
    "type": [
      "BillOfLading"
    ],
    "billOfLadingNumber": "991205182",
    "relatedDocuments": [
      {
        "@context": [
          "https://w3id.org/traceability/v1"
        ],
        "type": [
          "Purchase"
        ],
        "customer": {
          "type": [
            "Person"
          ],
          "email": "Willie78@example.net",
          "phoneNumber": "555-152-7258"
        }
      }
    ],

**Comment by OR13** [comment]
@mprorock @Therecanbeonlyone1969 @mkhraisha can I assign one of you to fix this?

**Comment by OR13** [comment]
Synthetic data generation should not nest contexts.

**Comment by Therecanbeonlyone1969** [comment]
@OR13 ... yeah i can do that together with the suggested enhancements etc.

**Comment by mkhraisha** [comment]
Happy to take over this, if needed.
my proposal is to modify all generator functions to return based on a flag.
I believe the conversion to generators that return a static blob should be done by individual contributors on the vocabulary they contributed to make sure it "makes sense" in business context.

**Comment by mkhraisha** [comment]
The agreement on the 29/06 call was to remove nested contexts and place them on the root level context object and remove duplicates.

So assuming: 

```
    "@context": [
      "https://w3id.org/traceability/v1"
    ],
    "type": [
      "BillOfLading"
    ],
    "billOfLadingNumber": "991205182",
    "relatedDocuments": [
      {
        "@context": [
          "SECOND CONTEXT"
        ],
        "type": [
          "Purchase"
        ],
        "customer": {
          "type": [
            "Person"
          ],
          "email": "Willie78@example.net",
          "phoneNumber": "555-152-7258"
        }
      }
    ],

```
this would change to 

```
 "@context": [
      "https://w3id.org/traceability/v1",
          "SECOND CONTEXT"
    ],
    "type": [
      "BillOfLading"
    ],
    "billOfLadingNumber": "991205182",
    "relatedDocuments": [
      {
        
        "type": [
          "Purchase"
        ],
        "customer": {
          "type": [
            "Person"
          ],
          "email": "Willie78@example.net",
          "phoneNumber": "555-152-7258"
        }
      }
    ],
    
    ```

**Comment by mkhraisha** [comment]
@msporny this is probably something you want to weigh in on.

**Comment by msporny** [comment]
> @msporny this is probably something you want to weigh in on.

Doing either is fine. If you're going to put contexts at the top level of a document, you may want to use scoped properties to narrow the fields where the second context comes into play. For example, you could scope by type for 'Purchase' -- examples of scoping by type can be found here:

https://github.com/digitalbazaar/ed25519-signature-2020-context/blob/master/contexts/ed25519-signature-2020-v1.jsonld#L11

If you scope by type, you don't pollute your top-level namespace. The problem with scoping by type/property is that if you want to pluck the purchase order out of the array above, you will have to make sure your code migrates the @context back into the purchase order. 

Personally, I'd prefer to keep the second context with the purchase order, but don't know the details of the use case to comment more than that.

> relatedDocuments

Minor nit, always use singular form for words to be consistent. All properties in JSON-LD (and graph-based data models in general) can always have one or more values associated with them. So, either all properties should be plural, or all properties should be singular. In general, you will have more singular properties than plural, which is why all properties tend to be singular form. It's not a requirement, but rather a stylistic one (that some people disagree with).

**Comment by OR13** [comment]
PROPOSAL: replace `$comment: string` with `$linkedData : object`

**Comment by OR13** [comment]
This proposal passed on todays call, I have the action of making these changes available.

**Comment by OR13** [comment]
> PROPOSAL: ask JSON-LD and JSON Schema WGs/teams for help with making JSON-LD Schema (or JSON Schema-LD) a more functional option (see issue #150)

We resolved this proposal as well.

**Comment by OR13** [comment]
> /me PROPOSAL: We will use OAS3.0 YAML Schemas in trace vocab, instead of JSON Schema in JSON

differed to next meeting, pending issues opened and feeback requested.

**Comment by OR13** [comment]
I have been taking notes here, please excuse my mess, I am moving these to separate issues.
