### ISSUE TITLE
We need a Roadmap

### ISSUE THREAD

**Issue by mkhraisha** [w3c-ccg/traceability-vocab#217]
This vocabulary has been in the works for a while, and we're would like to setup a stable version of it we can use at a certain point in the future.
I believe we need a Roadmap for this vocabulary, with milestones and a target v1 date etc.

**Comment by OR13** [comment]
We could use github projects, labels and releases and reserve some amount of call time to cover roadmap review moving forward.

**Comment by BenjaminMoe** [comment]
I think the low hanging fruit for a roadmap would be to try and define which verticals we want to support. But I think before that we need to get things in order. And make sure that we have all of our terms defined, we have documentation needed to participate, and visualizations for how our schemas are structured.

**Comment by BenjaminMoe** [comment]
Also we're probably going to need a strategy for updating schemas. Do we force credentials to be defined by a certain year? ie. `CommercialInvoice2022`, or do we have some other kind of versioning like `0.1.17`, that would allow for the context that was signed over to be retrieved so the credential does not get invalidated.

**Comment by BenjaminMoe** [comment]
- No undefined terms for context
- Schemas are defined and passing
- Missing list of credentials per vertical

**Comment by brownoxford** [comment]
@mkhraisha suggested action is to call out each vertical and which schemas are missing. Once we have these we are ready for V1.

**Comment by nissimsan** [comment]
Why would v1 not just be the list of credentials we have now?

**Comment by mkhraisha** [comment]
To ensure we aren't talking past each other, we should have a version for the context and vocabulary. see @OR13's comment https://github.com/w3c-ccg/traceability-vocab/issues/65#issuecomment-771840311

I believe "milestone" versions like v1/v2 etc should be cut at a point where we expect things have stabilized.
Obviously, the vocabulary would shift weekly as we keep moving things, and IMO looking at the rate of changes we have we are still not ready for a fixed version, we're still very unstable.

My goal is to find a list of vocabulary terms we can call "v1" once completed. on our end, we're happy with the current state, excepting the obvious EPCIS issues, but I would like to make sure that the other verticals are too.

The concrete question is this: Are there any terms that any of the verticals would like to delay cutting a v1 version for or are we all generally happy to call our current state "v1", and start working on "v2"?

**Comment by jmmski** [comment]
@mkhraisha @BenjaminMoe I am new to this group but have been following the space for a couple of years.  When you mention verticals.  Do you specifically mean the verticals in the Vocab Items as use cases 3.1 through 3.5

**Comment by BenjaminMoe** [comment]
Steps to move forward on this. 
1. Concrete proposals
2. Make it an agenda item to bring it up on the meetings

**Comment by BenjaminMoe** [comment]
I think there are a few criteria in order to nail down a version 1. In our case I think the focus should be quality over quantity. More schemas can be added in future versions, we should have a clear set of criteria for when a schema is "done". That way we can define a set of tests, and then track the progress. Once all of the schemas are defined, then we can bump the version to 1.0.

Aspects to take into consideration:
- Completeness of schemas
- State of the respec document
- State of the context
- Completeness of presentations

With respect to presentations, I don't think there is much that is likely to change in this respect. This seems like the easiest to nail down. 

For the respec document, this is probably something that we will need to freeze to say version 1. Not sure what and where we would need to change for this.

For the state of the context, this is the most abstract as I can see this being detrimental. If other projects map to our terms and we have `#trace-vocab` placeholder terms, then it would be hard for other projects to be able to use our terms. But this is a place where we might want to be selfish and say that we want to do what we can within a specific time-limit. We can get feedback on the frozen version, and address it in future versions.

The main focus is going to be the criteria for schemas. I think the main thing here is to define a checklist of criteria that could be made into CI checks to check the credentials against. Once all of the credentials are passing, then we can promote to version 1. 

- Mandatory and optional fields are defined
- Examples span the scope of the schema (schemas are narrowly defined to the examples they intend to portray)
- Descriptions are narrowly defined for the purpose they want to implement

**Comment by mkhraisha** [comment]
1. Is the intention of the spec to be published under a W3C working group or under a different SO like UN etc.

**Comment by mprorock** [comment]
we are covered right now (provided we don't get any core credentials like intent to import modified) - i say we cut a final cg spec as soon as possible and then move this stuff down a standards track during which we will support VC2.0

**Comment by mkhraisha** [comment]
we need to:
1. Go through every credential, schema and term, including types and predicates for each vertical and mark it as ready to be included in v1 or not.
2. pick a date where we will freeze the schemas/context and publish that frozen version


then we can publish: 
 1. Static Json Schema 
 2. Context on a high availability webhost, we can keep with Github pages.
