### ISSUE TITLE
Address LEI prefixing

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-vocab#232]
For example https://w3c-ccg.github.io/traceability-vocab/#LEIauthority

**Comment by VladimirAlexiev** [comment]
Look at the diagram in #272. I assume that https://github.com/w3c-ccg/traceability-vocab/blob/main/docs/openapi/components/schemas/common/LEIauthority.yml is intended to represent the middle `(I)` node on that diagram.

Current representation:
```
  {
    "type": "LEIauthority", -> traceability:LEIauthority
    "validationAuthorityID": "RA000004",  -> schema:identifier
    "otherValidationAuthorityID": "I9LWK4HR",  -> schema:taxID
    "validationAuthorityEntityID": "IR6TTVJ948RGX9YQDM4V"  -> schema:leiCode
  }
```

I think it needs to be corrected as follows:
```
  {
    "type": "LEIRegistryIdentifier", -> gleif-L1:BusinessRegistryIdentifier (1)
    "validationAuthorityID": "RA000004",  -> transparency:leiRalCode or gleif-L1:hasRegisteredAuthority (2)
    "nationalEntityID": "I9LWK4HR",  -> gleif-L1:hasEntityID (3)
             (4)
  }
```
1. This record is not an "authority" but a national business registry identifier (that was used for corroboration: `hasValidationIdentifier`)
2. I think a new data prop `transparency:leiRalCode` is needed because:
   - `gleif-L1:hasRegisteredAuthority` is an object property so can't be used with literal (eg "RA000004")
   - `gleif-base:hasTag` is too unspecific to use here (@rivettp do you agree?)
   - `schema:taxID` is not always correct because some of the RAL are not tax registries (but eg registers of financial institutions, foundations, insurers, etC)
   - Note: I've created the Wikidata prop "RAL code" https://www.wikidata.org/wiki/Property:P9487 and imported a bunch of values
3. "otherValidationAuthorityID" is completely wrong here, I think you swapped it with "validationAuthorityEntityID". But IMHO `nationalEntityID` is a more precise name than `validationAuthorityEntityID`
4. I've removed the last line because:
   - There is [gleif-L1:hasOtherAuthority](https://www.gleif.org/ontology/v1.0/L1/index-en.html#hasOtherAuthority L1/hasOtherAuthority) "A legacy / historical reference code of a registration authority which is not yet entered in the Registration Authorities Code List (RAL) maintained by GLEIF" but now all national authorities are in RAL, so that's not populated. 
   - Not all authorities have LEI (unlike the LOUs that issue LEIs, as you can see in the right `(I)` node)
   - There's no connection between RAL and LEI of authorities.

**Comment by OR13** [comment]
@VladimirAlexiev You know... I can't recall... its possible this term was previously prefixed, and has since been updated.

> BTW It's not a good idea to use both slash and hash /#.

IRC, this is a function of github pages hosting + w3id.org redirect...

https://w3.id.org/traceability/#LEIauthority
