### ISSUE TITLE
Generate a tree style visualization for each credential and render that next to the credential

### ISSUE THREAD

**Issue by BenjaminMoe** [w3c-ccg/traceability-vocab#462]
I wrote this script to track down where `Place` or `PostalAddress` was being used for https://github.com/w3c-ccg/traceability-vocab/issues/425. This script takes a path for a schema, and then traces through all of the child dependencies until it reaches a node with no children, or otherwise stop on `Place` or `Postal Address`.

These graphs should probably be generated to help visualized schemas, and be included somewhere in the repository as a markdown readme, or in the respec document to show the relationship between schemas. 

```javascript
"use strict";

const fs = require('fs')
const YAML = require('yamljs')

const credList = [
    // './credentials/MillTestReportCertificate.yml',
    './common/SteelProduct.yml',
    './common/Invoice.yml',
    './common/Purchase.yml',
    './common/ParcelDelivery.yml',
    './common/Organization.yml'
];

const scanSchema = (path, nodes, rel, parentIndex, propName) => {

    // We want to ignore Price Specification as it has no child nodes
    if(path.indexOf('PriceSpecification.yml') !== -1) {
        return;
    }

    const file = path.split('/').pop();
    const index = nodes.length;
    nodes.push(file);

    if(parentIndex !== -1) {
        rel.push([parentIndex, index, propName]);
    }

    // If we hit place or postal address, stop trace
    if(path.indexOf('Place.yml') !== -1 || path.indexOf('PostalAddress.yml') !== -1) {
        return;
    }

    // Otherwise, look for sub-scemas

    const schema = YAML.load(path);
    for(let key in schema.properties) {
        if(!schema.properties[key]['$ref']) {
            continue;
        }

        const ref = schema.properties[key]['$ref'];
        const leaf = ref.split('/').pop();
        scanSchema(`./common/${leaf}`, nodes, rel, index, key);
    }

}

credList.forEach( name => {

    console.log('Starting check for', name);

    const nodes = [];
    const rel = [];

    scanSchema(name, nodes, rel, -1);
    console.log(nodes, rel);

    const text = ['flowchart TB'];
    nodes.forEach( (node, index) => {
        text.push(`id${index}(${node})`);
    });
    rel.forEach( ([a, b, prop]) => {
        text.push(`id${a} -->|${prop}| id${b}`);
    });

    const leaf = name.split('/').pop();
    const base = leaf.split('.').shift();

    fs.writeFileSync(`./graphs/${base}.md`, text.join('\n'));
});
```

### Example Output

This is `organization.yml`. 

```md
flowchart TB
id0(Organization.yml)
id1(PostalAddress.yml)
id2(Place.yml)
id3(Brand.yml)
id4(ContactPoint.yml)
id5(PostalAddress.yml)
id0 -->|address| id1
id0 -->|location| id2
id0 -->|brand| id3
id0 -->|contactPoint| id4
id4 -->|address| id5
```

###Example Rendered:

This is `invoice.yml`

![mermaid-diagram-2022-07-05-223712](https://user-images.githubusercontent.com/86194145/177342632-9431914f-b19a-4c27-a81a-995972151c68.png)

**Comment by BenjaminMoe** [comment]
Cross link: https://github.com/w3c-ccg/traceability-vocab/issues/443

**Comment by VladimirAlexiev** [comment]
@BenjaminMoe Can I convince you to use PlantUML instead of Mermaid?

The syntax is similar (I've omitted a leading `@` else github renders the picture instead of the code!):
```plantuml
startuml
hide empty methods
hide empty attributes
hide circle

class id0 as "Organization.yml"
class id1 as "PostalAddress.yml"
class id2 as "Place.yml"
class id3 as "Brand.yml"
class id4 as "ContactPoint.yml"
class id5 as "PostalAddress.yml"
id0 --> id1 : address
id0 --> id2 : location
id0 --> id3 : brand
id0 --> id4 : contactPoint
id4 --> id5 : address
@enduml
```
Result (you can also [see that on the plantuml server](http://www.plantuml.com/plantuml/uml/TP0xhiCW401xJe7S--d5doP5v2G7YA-mXbMCn2U2TU6SFXXR4HHfPrRii4CWyBGOpMObaQDvqSeDqknao14GUJKjX0SLoWkDZ0aD8N0b_pa4NZty4wnw0obd_rQZgwy_9J-wk4vVfVGOGZdGx0CQ19QYJUBcmSfIT4dSdIKGD3fbgVJzhvLRRLrVKjMPmwuosaIgdKY_o70RyRHbPAoBJ6G5BA93zTdR0rePR_m1)):

![](http://www.plantuml.com/plantuml/png/TP0xhiCW401xJe7S--d5doP5v2G7YA-mXbMCn2U2TU6SFXXR4HHfPrRii4CWyBGOpMObaQDvqSeDqknao14GUJKjX0SLoWkDZ0aD8N0b_pa4NZty4wnw0obd_rQZgwy_9J-wk4vVfVGOGZdGx0CQ19QYJUBcmSfIT4dSdIKGD3fbgVJzhvLRRLrVKjMPmwuosaIgdKY_o70RyRHbPAoBJ6G5BA93zTdR0rePR_m1)


Mermaid is nice, there's a mobile app and a book...
But PlantUML can just do so much more !
[Sequence](https://plantuml.com/sequence-diagram), [Use Case](https://plantuml.com/use-case-diagram), [Class](https://plantuml.com/class-diagram), [Activity](https://plantuml.com/activity-diagram-legacy), [Activity ](https://plantuml.com/activity-diagram-beta), [Component](https://plantuml.com/component-diagram), [State](https://plantuml.com/state-diagram), [Object](https://plantuml.com/object-diagram), [Deployment](https://plantuml.com/deployment-diagram), [Timing](https://plantuml.com/timing-diagram), [Network](https://plantuml.com/nwdiag), [Wireframe](https://plantuml.com/salt), [Archimate](https://plantuml.com/archimate-diagram), [Gantt](https://plantuml.com/gantt-diagram), [MindMap](https://plantuml.com/mindmap-diagram), [WBS](https://plantuml.com/wbs-diagram), [JSON](https://plantuml.com/json), [YAML](https://plantuml.com/yaml).

I use it for RDF diagrams (with my tool rdfpuml, part of rdf2rml). Eg https://gist.github.com/VladimirAlexiev/4ebf7d72dac192a03adf10b6385e7ad4

**Comment by mkhraisha** [comment]
here is an example of a really good visualization we may want to use: https://onerecord.iata.org/ontology/webvowl/index.html#

**Comment by BenjaminMoe** [comment]
More examples: https://github.com/BlockchainCommons/Gordian/blob/master/Docs/Envelope-Use-Cases-Software.md#anonymous-signing

**Comment by OR13** [comment]
Some of the work in: https://github.com/transmute-industries/merkle-proof might be useful.

**Comment by OR13** [comment]
We do have this...

<img width="808" alt="Screen Shot 2023-01-27 at 12 47 52 PM" src="https://user-images.githubusercontent.com/8295856/215169723-6554dd90-a9aa-42fd-b7ba-d02733abb7ca.png">

**Comment by BenjaminMoe** [comment]
@OR13 that's a massive visualization for all of the credentials. The issue being suggested here is that we provide better visualizations for each credentials to show that something like `IntentToImport` has `importer`, `expoter`, and `date`, and which fields they are made of.

**Comment by OR13** [comment]
its possible to modify the code and generate a tree style visualization for each credential.

**Comment by BenjaminMoe** [comment]
> its possible to modify the code and generate a tree style visualization for each credential... and render that on demand, next to the credential.

That's a much better summary of the intent of this issue.

**Comment by nissimsan** [comment]
@mkhraisha, do you still want to do this?

**Comment by BenjaminMoe** [comment]
My suggestion is that we can close this, since we're moving away from the common schema approach for building credentials.
