### ISSUE TITLE
Review Science On Schema.Org (SOSO) Guidance Documents

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-vocab#477]
https://github.com/ESIPFed/science-on-schema.org/

@nissimsan @BenjaminMoe can you take a pass at reading this and identify any strong areas of allignment?

**Comment by BenjaminMoe** [comment]
I read though https://github.com/ESIPFed/science-on-schema.org/blob/master/guides/Dataset.md. It looks the like the focus is providing specific examples for how scientists can structure JSON data to take advtage of the terms defined by schema.org with linked data.

```
{
  "@context": "https://schema.org/",
  "@type": "Dataset",
  "name": "Dataset shell for example DefinedTerm keywords",
  "keywords": [
    {
      "@type": "DefinedTerm",
      "name": "OCEANS",
      "inDefinedTermSet": "https://gcmd.earthdata.nasa.gov/kms/concepts/concept_scheme/sciencekeywords",
      "url": "https://gcmd.earthdata.nasa.gov/kms/concept/91697b7d-8f2b-4954-850e-61d5f61c867d",
      "termCode": "91697b7d-8f2b-4954-850e-61d5f61c867d"
    },
    {
      "@type": "DefinedTerm",
      "name": "ice core studies",
      "inDefinedTermSet": "https://vocabularyserver.com/cnr/ml/snowterm/en/",
      "url": "https://vocabularyserver.com/cnr/ml/snowterm/en/index.php?tema=29330",
      "identifier": {
        "@type": "PropertyValue",
        "propertyID": "https://registry.identifiers.org/registry/ark",
        "value": "ark:/99152/t3v4yo3eeqepj0",
        "url": "https://vocabularyserver.com/cnr/ml/snowterm/en/?ark=ark:/99152/t3v4yo3eeqepj0"
      }
    },
    {
      "@type": "DefinedTerm",
      "name": "Baked Clay",
      "inDefinedTermSet": "https://www2.earthref.org/vocabularies/controlled"
    }
  ]
}
```

In terms of the places of alignment. I think there are two main points. The first point is their documentation is _amazing_. I think that this is definitely we would want to communicate the primary goal of traceability-vocab and how people can take advantage of it. Explain our convention, examples, and how those examples and conventions are able to become RDF rich datasets with examples. 

Which is something that I think we could be better with https://github.com/w3c-ccg/traceability-vocab/issues/462 by using diagrams to convey that information.

And the other point that [science-on-schema.org](https://github.com/ESIPFed/science-on-schema.org) does an amazing job of is `@type`, so that you can clearly see which elements are JSON-LD specific. I don't know if that's intentional or not, but i'm not a fan of the automatic mapping of `type` to `@type` in the Verifiable Credential context, and that might be something we're stuck with.
