### ISSUE TITLE
List of documents that could be added to trace-vocab

### ISSUE THREAD

**Issue by BenjaminMoe** [w3c-ccg/traceability-vocab#546]
These are documents that we gathered requirements for, but ended up not adding to trace-vocab based on time constraints. Putting them here in case someone can pick them up. 

1. Form 214: FTZ Admission schema - [https://www.cbp.gov/sites/default/files/assets/documents/2021-Sep/CBP Form 0214.pdf](https://www.cbp.gov/sites/default/files/assets/documents/2021-Sep/CBP%20Form%200214.pdf)

2. Sales Order schema - A sales order is a commercial document -- prepared by a seller and issued to a customer -- confirming the sale of goods or services involved in a given transaction. The document contains details about the sale, including the quantity, quality, and price of any goods or services exchanged.

3. Delivery Order schema -  I've seen this used in the freight forwarding world. A delivery order is a document issued by the shipper, carrier or freight forwarder instructing the shipping line and the port operator to turn over the cargo to the party responsible to carry out the import activities. 

 4. Certificate of Free Sale schema - A Certificate of Free Sale is used when you are registering a new product in a country. You’re essentially informing the customs authority in that country, “I’m going to start importing, and here are my support documents that confirm these are legal to sell in the country of manufacture.”

 5. Air Cargo Advance Screening (ACAS) schema - Entry for for air, similar to the 10+2 for ocean [https://www.cbp.gov/sites/default/files/assets/documents/2018-Jun/ACAS Fact Sheet 060518A FINAL.pdf](https://www.cbp.gov/sites/default/files/assets/documents/2018-Jun/ACAS%20Fact%20Sheet%20060518A%20FINAL.pdf)

 6. EPA 3540-1: Notice of Arrival of Pesticides and Devices schema - Importer who wishes to import pesticides or devices into the US must fill this form out https://www.epa.gov/sites/default/files/2013-09/documents/noaform_1.pdf
 
7. [Proof of Delivery img](https://user-images.githubusercontent.com/86194145/186871736-4c23f421-e47d-4731-b32f-cbbba554bee6.png)

8. [Declaration of Dangerous Goods img](https://user-images.githubusercontent.com/86194145/186901385-62cfcfbe-6ab7-4f68-baf1-c6bb0fde1c72.png)

9. [multi-modal dangerous goods img](https://user-images.githubusercontent.com/86194145/186902387-8f8b2018-4ba8-4fee-874d-4cbf002936e8.png)

10.  USFWS Form 3-177: Declaration for Importation or Exportation of Fish or Wildlife schema - https://www.fws.gov/sites/default/files/documents/Wildlife%20Shipments%20-%203-177%202022%281%29.pdf

11. FIATA House Bill of Lading - https://unece.org/digitalization/press/electronic-fiata-multimodal-bill-lading-data-standard-available-open-source https://github.com/FIATA/eFBL

12. APHIS: Form 287 Emergency Action Notification  [APHIS 287   523-1](https://user-images.githubusercontent.com/86194145/187139279-75a08e71-7bbe-41b1-bc8b-18ac6433364b.jpg) [APHIS 287   523-2](https://user-images.githubusercontent.com/86194145/187139302-1af97cb8-3781-4e94-acc6-b2f26ce7d732.jpg)
 
13. APHIS: Form 523 Emergency Action Notification w/ Broker/Importer [APHIS 287   523-1-1](https://user-images.githubusercontent.com/86194145/187139610-b1e1afc5-6912-449f-b75b-f9b9efce21e8.jpg) [APHIS 287   523-1-2](https://user-images.githubusercontent.com/86194145/187139886-bef9b6ac-912f-4279-990e-bf6dda66b5d0.jpg)

**Comment by TallTed** [comment]
I wonder whether "unsatisfied" would be more accurate than "unused"?

**Comment by BenjaminMoe** [comment]
I think the difference is that "unsatisfied" is these were documents that were _required_ but not delivered. The context here is these were documents we were considering to add but cut back due to time constraints, so I leaned towards "unused".

**Comment by TallTed** [comment]
I think I understand what you're saying.

I also think that, in the typical W3 naming of things, these "common business documents" ought to be considered _Use Cases_, each of which does indeed have _Requirements_, all of which would typically be collected in a UCR (sometimes putting the UC into one doc, and the R in another; more often, collecting them into a single doc).

The Requirements of various of our Use Cases have been Satisfied (via inclusion in trace-vocab), while the Requirements of _these_ Use Cases do indeed remain Unsatisfied, and these Use Cases may not yet be fully addressed by the output of this group's work -- though they may be _partially_ addressed by properties built into the trace-vocab in order to satisfy the Requirements of other Use Cases.

I think it's worth titling this tracking issue with these terms, as they're commonly used in the W3C, and creating another issue per real-world document -- i.e., per remaining Use Case -- as these will be smaller, and more likely to be picked up by someone with some spare cycles, for future evolution and growth of trace-vocab.  Such efforts should start by ticking off the properties of each document that are already covered by existing trace-vocab properties, leading to a reduced list of Requirements for each Use Case, and thence to extending/improving the next version of trace-vocab.

**Comment by BenjaminMoe** [comment]
> I think it's worth titling this tracking issue with these terms, as they're commonly used in the W3C, and creating another issue per real-world document -- i.e., per remaining Use Case -- as these will be smaller, and more likely to be picked up by someone with some spare cycles

I wanted to avoid creating too many issues at once to start off with. But I tend to agree that splitting out each document into it's own issue would allow us to track if there is interest in adding these specific documents. And closing out specific documents that don't get picked up.

**Comment by mkhraisha** [comment]
big +1 to splitting these up into individual issues, makes assigning myself to the ones I can work on much easier. I think this issue should be closed and individual per document issues opened, overlap with existing vocabulary elements should not be an impediment to opening those issues, we can do that work as we go forward.

**Comment by nissimsan** [comment]
General agreement on the call. 

@BenjaminMoe , please improve the title.

**Comment by BenjaminMoe** [comment]
We have no hard requirements to implement these. Closing.
