### ISSUE TITLE
For mock numbers "555" should be prefix, not area code

### ISSUE THREAD

**Issue by rhofvendahl** [w3c-ccg/traceability-vocab#640]
AFAIK good practice for mock phone numbers is to use 555 as the prefix (the three digits after area code), along the lines of "(xxx) 555-xxxx"). [Here's](https://en.wikipedia.org/wiki/555_(telephone_number)) a wiki article on use of the 555 prefix, and [another](https://en.wikipedia.org/wiki/Fictitious_telephone_number) on mock phone numbers generally.

Currently most of the mock numbers in our schema examples either use 555 as the area code, or not at all. I propose we update all numbers to use the format XXX-555-XXXX.

I'd be willing to implement this, if there are no objections.

**Comment by rhofvendahl** [comment]
Also: I'd be interested in hearing opinions on `+1-xxx-xxx-xxxx` format vs just `xxx-xxx-xxxx`. Currently it's a mix, is that what we want?

**Comment by TallTed** [comment]
`+1` is the country code for USA, Canada, and various smaller entities that also participate in the [NANPA](https://en.wikipedia.org/wiki/North_American_Numbering_Plan).  It is appropriate to use this for all such (fake or real) numbers.

Any fake numbers we're putting in other countries should get the relevant (real) country code, e.g., `+44` for the UK.

Omitting the country code may lead to various mischief including (intended or not) DDOS attacks by software being tested (or deployed!) with some connection to the fake data we're providing... because by omitting (for instance) the `+1`, the first dialed digits may be the country code for another country....

All of which is to say — I'd convert from the mix to always include the `+1` on NANPA numbers.

**Comment by OR13** [comment]
I think we did this, close it

**Comment by nissimsan** [comment]
We did this.
