### ISSUE TITLE
GS1KeyCredential is not defined in context

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-vocab#707]
This file is expected to define "GS1KeyCredential" but does not: https://ref.gs1.org/gs1/vc/licence-context/

**Comment by OR13** [comment]
This example is also wrong: https://w3c-ccg.github.io/traceability-vocab/#example-30

Need to define:

```
"tradeItemDescription": "Never Give Up NRG Drink",
"tradeItemImageURL": "https://www.example.com/assets/7541234555551.png",
```

**Comment by paulfdietrich** [comment]
Investingating

**Comment by KDean-GS1** [comment]
GS1KeyCredential is not a licensing artefact; it can be found in declaration-context, which provides the foundation for making data declarations.

Detailed data declarations may be found in trade-item-context (GTIN) and party-context (GLN).

**Comment by OR13** [comment]
hmm, so we have the wrong context...

need to add https://ref.gs1.org/gs1/vc/trade-item-context/

**Comment by OR13** [comment]
There are several GS1 contexts listed here: https://ref.gs1.org/gs1/vc/

We need to make sure the right contexts are added to the right credentials to prevent undefined terms.

- https://ref.gs1.org/gs1/vc/declaration-context/
- https://ref.gs1.org/gs1/vc/licence-context/
- https://ref.gs1.org/gs1/vc/party-context/
- https://ref.gs1.org/gs1/vc/trade-item-context/

**Comment by OR13** [comment]
@nissimsan ^ might only take you a second to fix this, given the information above.

**Comment by nissimsan** [comment]
Right, thanks, this is helpful. Here is progress: https://github.com/w3c-ccg/traceability-vocab/pull/709. This should eliminate the undefined terms. 

There are still a few remaining rough edges... 

- I still had to keep `https://ref.gs1.org/gs1/vc/license-context/` on GS1KeyCredential because `extendsCredential` isn't defined on `declaration-context`. 
- Similarly, had to include `https://ref.gs1.org/gs1/vc/declaration-context/` on GS1DataCredential because `keyAuthorisation` is missing in `trade-item-context`
- Also, note that it's spelling `keyAuthorisation` in the example, but `keyAuthorization` in the context. I changed to example to make it fit. 

I would recommend clubbing together the four different contexts into one. Juggling them separately adds unnecessary complexity.

**Comment by nissimsan** [comment]
Noticing https://w3c-ccg.github.io/traceability-vocab/#GS1DelegationCredential also needs to be switched to https://ref.gs1.org/gs1/vc/declaration-context/. Will do that now...

**Comment by nissimsan** [comment]
https://github.com/w3c-ccg/traceability-vocab/pull/715

**Comment by nissimsan** [comment]
Seems fixed.
